### ISSUE TITLE
The RS232 interface does not work properly

### ISSUE THREAD

**Issue by UeberDaniel** [WildernessLabs/Meadow.Core#341]
When I want to upload data to the F7FeatherV2 with ISerialMessagePort, only a part of it arrives. Tested with 1024 bytes of data, with:
` serialPort = Device.CreateSerialMessagePort(
                new SerialPortName("COM4", "ttyS1", Resolver.Device),
                prefixDelimiter:  new byte[] {0x01, 0x10, 0x02, 0x20, 0x04, 0x40, 0x08, 0x80},
                preserveDelimiter: false,
                messageLength: 1032,
                baudRate: 9600,
                parity: Parity.None,
                readBufferSize: 2048
                );`

Played around with the baudrate, prefix and suffix delimiter, parity and readBufferSize. Somtimes there are ~200, ~100 or ~400 correct, the the rest are zeros. Tested with an uploaded file via HTerm as well as with a console application.

![rs232](https://github.com/WildernessLabs/Meadow.Core/assets/10797624/21031b01-ee44-4fe9-91a1-d4db84ad8859)

ISerialPort produces the same results.

The data is also transferred correctly(Tested with a sequence of 0x00 and 0xFF):
[data.csv](https://github.com/WildernessLabs/Meadow.Core/files/12149474/data.csv)

**Comment by ctacke** [comment]
Cannot reproduce.

The above is unclear exactly how to repro, but I used the following.

On the meadow (F7FeatherV2)
```
var port = Device
    .PlatformOS
    .GetSerialPortName("com4")
    ?.CreateSerialPort(19200, 8, Parity.None, StopBits.One, 2048)
    ?? throw new System.Exception("com4 not found");

var buffer = new byte[4096];

port.Open();

while (true)
{
    var read = port.Read(buffer, 0, buffer.Length);

    if (read == 0)
    {
        Thread.Sleep(1000);
        continue;
    }

    Resolver.Log.Info($"rx {read:N4} bytes");
    Resolver.Log.Info($"  {Encoding.ASCII.GetString(buffer, 0, read)}");
}
```
on a PC
```
var port = new SerialPort("COM5", 19200);
port.Open();

var message = "On the 24th of February, 1815, the look-out at Notre-Dame de la Garde signalled the three-master, the Pharaon from Smyrna, Trieste, and Naples";
var messages = message.Split(' ', StringSplitOptions.RemoveEmptyEntries);

while (true)
{
    for (var i = 0; i < messages.Length; i++)
    {
        var data = Encoding.ASCII.GetBytes(messages[i]);
        port.Write(data, 0, data.Length);
        Thread.Sleep(2000);
    }
}
```
And it worked as expected.

**Comment by UeberDaniel** [comment]
@ctacke, i tested it with my testfile and HTerm, it produces the same error, the problem is the length of the datastream. You tested it with a message ~150 byte, but that is not enough to reproduce this error.

I used this to produce the datastream and the testfile:

```
            byte[] prefix = new byte[] { 0x01, 0x10, 0x02, 0x20, 0x04, 0x40, 0x08, 0x80 };
            byte[] buffer = new byte[1032];

            for(int i = 0; i < buffer.Length; i++)
            {
                buffer[i++] = 0xFF;
                buffer[i] = 0x00;
            }

            for (int j = 0; j < prefix.Length; j++)
            {
                buffer[j] = prefix[j];
            }
            File.WriteAllBytes(@"D:\file.txt", buffer);
            _serialPort.Write(buffer, 0, buffer.Length);
```
![Screenshot 2023-07-26 185132](https://github.com/WildernessLabs/Meadow.Core/assets/10797624/b4094b54-b4fa-4457-bc40-a056516bee43)

Here is my generated testfile for HTerm: [file.txt](https://github.com/WildernessLabs/Meadow.Core/files/12175232/file.txt)
